
INSERT INTO Eastern_European (id, descrip)
VALUES (1, "Eastern Europe is a vast area encompassing many cultures including Slavic, Hungarian, Romanian, and Baltic peoples. The climate of Eastern Europe has been extremely infulencial its peoples' food. The cold climate has made it difficult to grow fruits and vegetables, and farmers have had to rely on potatoes, grains, and dairy products as well as fishing, hunting, and herding. The cuisine of Eastern Europe is hearty, heavy on the starches, sauerkraut, and meats.our cream and dill are frequent accompaniments, creating a unique balance of savory and tangy tastes. Desserts like strudel and honey-soaked pastries provide a sweet finale to this diverse and satisfying culinary heritage.", `Russian table traditions revolve around toasts. They often start with "Za zdorovye!" (To health!) or "Za lyubov!" (To love!). Toasts express goodwill, gratitude, and respect. At the table, it's important to make eye contact and clink glasses with everyone.`);

INSERT INTO Italian (id, descrip)
VALUES (2, "Indulge in a culinary odyssey to the sun-kissed shores and rolling hills of Italy as we invite you to savor the soulful and time-honored treasures of Italian gastronomy. From the rustic simplicity of Tuscan cuisine to the exquisite elegance of Venetian seafood, embark on a journey that celebrates the art of 'la dolce vita.' Our site is your passport to a world of homemade pasta, aromatic herbs, and the warm embrace of family recipes passed down through generations. You'll uncover the secrets of perfectly al dente pasta, sumptuous risottos, and the blissful marriage of fresh ingredients. Let the enticing aromas of basil and garlic transport you to the bustling piazzas and charming trattorias of Italy. Whether you're a seasoned chef or a passionate novice, join us in experiencing the joy of Italian cooking – where each dish is a love letter to tradition and taste.", " "); 

INSERT INTO Indian (id, descrip)
VALUES (3, "Located in South Asia, India is the most populous country in the world. Traditional Indian food uses a variety of herbs and spices. Dishes include rice, curries, sauces and tandoor style meats. The recipes listed here are the most common and easiest to prepare. Enjoy.", "When dining in India, always use your right hand. Even if you’re a lefty, you must use your right hand for eating. Indians consider the use of the left hand to be unclean and offensive. So the left hand remains dry and is only used for drinking water or passing dishes."); 

INSERT INTO Chinese (id, descrip)
VALUES (4, "Embark on a culinary journey to the heart of China as we take you on a delectable adventure through the rich tapestry of Chinese cuisine. Discover the tantalizing flavors, vibrant colors, and harmonious balance that define this ancient culinary tradition. From the fiery embrace of Sichuan dishes to the delicate artistry of dim sum, site invites you to savor the essence of China's diverse regional cuisines. With step-by-step recipes and expert tips, you'll master the art of wok cooking, noodle crafting, and sauce perfection. Get ready to create unforgettable dishes that transport your taste buds to the bustling streets of Beijing, the tranquil tea gardens of Hangzhou, and beyond. Join us in celebrating the magic of Chinese cooking – where every dish tells a story, and every bite is an enchanting voyage. ", " "); 

INSERT INTO American (id, descrip)
VALUES (5, "Join us on a delectable journey across the highways of American food culture. From the soulful comfort of Southern barbecue to the bold and innovative dishes of the West Coast, our cookbook invites you to explore the flavors and stories that define American cuisine. Discover the art of crafting the perfect burger, the secret to finger-licking fried chicken, and the joy of savoring a slice of homemade apple pie. With a bounty of recipes that span coast to coast, we invite you to embrace the melting pot of culinary traditions that have shaped American cooking. Whether you're a lover of classic diner fare, regional specialties, or contemporary fusion cuisine, America has something for everyone. Join us in celebrating the delicious diversity of American food, where each dish is a slice of history and a taste of home. ", " "); 

NSERT INTO Mexican (id, descrip)
VALUES (1, "Embark on a mouthwatering excursion to the heart of Mexico as our recipes invite you to savor the bold and authentic flavors of this beloved culinary tradition. From the fiery salsas of Oaxaca to the comforting embrace of Yucatecan tamales, we'll unveils the secrets of great Mexican cooking. Discover the art of crafting perfect tacos, the joy of handmade tortillas, and the depth of flavors in traditional mole sauces. With recipes steeped in tradition and our expert guidance, you'll master the techniques and spices that bring the spirit of Mexico to your kitchen. Join us in celebrating the vibrant culture, the warm hospitality, and the rich history that infuse every dish in Mexican cuisine. Whether you're a seasoned cook or a passionate novice, our cookbook is your ticket to a fiesta of flavors, where every bite is a taste of Mexico's soul.", " ");